kind: Pod
apiVersion: v1
metadata:
  name: senko-bot
  namespace: default
  uid: 3fd84e5c-e38f-4923-bd50-f3d1d66b4254
  resourceVersion: '1458'
  creationTimestamp: '2022-10-29T11:51:00Z'
  labels:
    run: senko-bot
  annotations:
    cni.projectcalico.org/containerID: 9cefeff21d48759f526a7f23983227e5f35bd06fce8ec2e9f30452d56791ac14
    cni.projectcalico.org/podIP: 172.30.16.203/32
    cni.projectcalico.org/podIPs: 172.30.16.203/32
    kubernetes.io/psp: ibm-privileged-psp
  managedFields:
    - manager: kubectl-run
      operation: Update
      apiVersion: v1
      time: '2022-10-29T11:51:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:run: {}
        f:spec:
          f:containers:
            k:{"name":"senko-bot"}:
              .: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2022-10-29T11:51:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:cni.projectcalico.org/containerID: {}
            f:cni.projectcalico.org/podIP: {}
            f:cni.projectcalico.org/podIPs: {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2022-10-29T11:51:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"172.30.16.203"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
spec:
  volumes:
    - name: kube-api-access-5srfq
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: senko-bot
      image: us.icr.io/senko_bot_namespace/senko_bot:v1
      resources: {}
      volumeMounts:
        - name: kube-api-access-5srfq
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: 10.144.185.224
  securityContext: {}
  imagePullSecrets:
    - name: all-icr-io
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 600
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 600
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-10-29T11:51:01Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-10-29T11:51:15Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-10-29T11:51:15Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-10-29T11:51:01Z'
  hostIP: 10.144.185.224
  podIP: 172.30.16.203
  podIPs:
    - ip: 172.30.16.203
  startTime: '2022-10-29T11:51:01Z'
  containerStatuses:
    - name: senko-bot
      state:
        running:
          startedAt: '2022-10-29T11:51:15Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: us.icr.io/senko_bot_namespace/senko_bot:v1
      imageID: >-
        us.icr.io/senko_bot_namespace/senko_bot@sha256:dd3a1cb1f81ad3fceb11202631379115136d8a4f8d00ec0bb1bd1d8d82f470c5
      containerID: >-
        containerd://9aa61f4ecfb983caaf7d273cf054041596a8add1f9ee1b54cf7dc368a6643309
      started: true
  qosClass: BestEffort
